name: CI Banking System
on: 
  pull_request: 
    branches: ["main"]

jobs: 
    lint:
      uses: ./.github/workflows/lint.yaml
      
    build:
      name: "Test"
      runs-on: ubuntu-latest
      needs: [lint]
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with: 
            node-version: 20.x
            
        - run: npm install
        - run: npm run test
        
        - name: Upload result to codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
