name: Deployment
on: 
  push: 
    branches: ["main"]

jobs: 
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GCP Compute Engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          username: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          script: |
            cd /home/naufal2404ginting
            cd deployment
            cd f-bee24001186-km7-nag-basicbankingsystem-ch2
            git pull
            npm install
            npx prisma migrate deploy
            npx pm2 restart BasicBankingSystem
