name: Deployment
on: 
  push: 
    branches: ["main"]

jobs: 
  deploy:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to GCP Compute Engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          port: ${{secrets.PORT}}
          username: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          script: |
            cd /home/naufal2404ginting
            cd f-bee24001186-km7-nag-basicbankingsystem-ch2
            git pull
            npm install
            npx prisma migrate deploy
            npx pm2 restart BasicBankingSystem

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install depedencies
        run: npm install --frozen-lockfile

      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{secrets.GCP_SA_KEY}}
          project_id: ${{secrets.GCP_PROJECT_ID}}

      - name: Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: env.yaml
        run: |
          touch env.yaml
          echo "${{secrets.ENV_YAML}}" >> env.yaml

      - name: Deploy to APP Engine
        run: gcloud app deploy

      - name: Clean up files
        run: rm app.yaml env.yaml